# Generated by Django 4.2 on 2023-06-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_complaint_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='name',
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed')], default=1),
        ),
    ]
