# Generated by Django 4.2 on 2023-06-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_complaint_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='discription',
            field=models.TextField(default=''),
        ),
    ]
