# Generated by Django 4.2 on 2023-06-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_complaint_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='discription',
            new_name='description',
        ),
    ]
